name: Install Docker and Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  install-docker-and-pterodactyl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      
      - name: Add Docker's official GPG key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      
      - name: Add Docker repository
        run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      
      - name: Update package index
        run: |
          sudo apt-get update
      
      - name: Install Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      
      - name: Clone Pterodactyl repository
        run: |
          git clone https://github.com/pterodactyl/panel.git /tmp/panel
      
      - name: Set up Pterodactyl
        run: |
          cd /tmp/panel
          chmod +x ./setup.sh
          ./setup.sh
          php artisan p:environment:setup \
            --dbHost="localhost" \
            --dbPort="3306" \
            --dbName="pterodactyl" \
            --dbUser="pterodactyl" \
            --dbPass="pterodactyl" \
            --dbPrefix="" \
            --appUrl="http://example.com" \
            --appTimezone="UTC" \
            --appLocale="en" \
            --queueDriver="sync" \
            --cacheDriver="redis" \
            --sessionDriver="redis" \
            --mailDriver="smtp" \
            --mailHost="smtp.mailtrap.io" \
            --mailPort="2525" \
            --mailUser="" \
            --mailPass="" \
            --mailFrom="mail@example.com" \
            --mailEncryption="tls"
          php artisan key:generate --force
          php artisan migrate --seed --force
          php artisan p:user:make --email="shrpy18@gmail.com" --username="shrpy" --password="shrpy18@" --admin=1
      
      - name: Build and start Pterodactyl services
        run: |
          cd /tmp/panel
          docker-compose up -d

      - name: Wait for Pterodactyl services to start
        run: sleep 60
      
      - name: Check Pterodactyl panel status
        run: |
          sleep 10
          curl -sI http://localhost:8080 | grep "200 OK"

      - name: Check Pterodactyl wings status
        run: |
          sleep 10
          curl -sI http://localhost:8081 | grep "200 OK"

      - name: Access Pterodactyl panel
        run: |
          sleep 10
          curl -I http://localhost:8080

      - name: Access Pterodactyl wings
        run: |
          sleep 10
          curl -I http://localhost:8081
