name: Create VPS with Web Terminal

on:
  push:
    branches:
      - main

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t web-terminal .


      - name: Run Docker container
        run: docker run -d --name web-terminal -p 4200:4200 web-terminal

      - name: Delay for container to start
        run: sleep 10

      - name: Obtain public IP and Display Wings Link
        id: public_ip
        run: |
          apt-get update && apt-get install -y curl
          echo "::set-output name=ip::$(curl -s https://api.ipify.org)"
          echo "Public Link: http://$(curl -s https://api.ipify.org):8081"
