name: Install Docker and Pterodactyl Panel

on:
  push:
    branches:
      - main

jobs:
  install-docker-and-panel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Clone Pterodactyl Dockerized Panel
        run: |
          git clone https://github.com/pterodactyl/panel.git /tmp/panel

      - name: Configure Pterodactyl Panel
        run: |
          cd /tmp/panel
          cp .env.example .env
          docker-compose build --pull
          docker-compose up -d

      - name: Wait for Pterodactyl Panel to Start
        run: sleep 60

      - name: Add Admin User
        run: |
          docker-compose exec -T panel php artisan p:user:make --email="shrpy18@gmail.com" --username="shrpy" --password="shrpy18@" --admin=1

      - name: Obtain Public IP
        id: public_ip
        run: echo "::set-output name=ip::$(curl -s ifconfig.me)"

      - name: Display Panel and Wings Links
        run: |
          echo "Panel Link: http://${{ steps.public_ip.outputs.ip }}:8080"
          echo "Wings Link: http://${{ steps.public_ip.outputs.ip }}:8081"
